// <auto-generated />
using System;
using AdaSoftLibrary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaSoftLibrary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240621114830_AddBookYear")]
    partial class AddBookYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("AdaSoftLibrary.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("AdaSoftLibrary.Domain.Entities.Borrowed", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Borrowed");
                });

            modelBuilder.Entity("AdaSoftLibrary.Domain.Entities.Borrowed", b =>
                {
                    b.HasOne("AdaSoftLibrary.Domain.Entities.Book", "Book")
                        .WithOne("Borrowed")
                        .HasForeignKey("AdaSoftLibrary.Domain.Entities.Borrowed", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AdaSoftLibrary.Domain.Entities.Book", b =>
                {
                    b.Navigation("Borrowed");
                });
#pragma warning restore 612, 618
        }
    }
}
