### YamlMime:ManagedReference
items:
- uid: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command
  commentId: T:AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command
  id: ReturnBook.Command
  parent: AdaSoftLibrary.Application.Books.Commands
  children:
  - AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor(System.Int32)
  - AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
  langs:
  - csharp
  - vb
  name: ReturnBook.Command
  nameWithType: ReturnBook.Command
  fullName: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command
  type: Class
  source:
    remote:
      path: src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
      branch: master
      repo: https://github.com/ppucik/AdaSoftLibrary.git
    id: Command
    path: ../src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
    startLine: 14
  assemblies:
  - AdaSoftLibrary.Application
  namespace: AdaSoftLibrary.Application.Books.Commands
  syntax:
    content: 'public class ReturnBook.Command : IRequest<Unit>, IBaseRequest'
    content.vb: Public Class ReturnBook.Command Implements IRequest(Of Unit), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{MediatR.Unit}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor(System.Int32)
  commentId: M:AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command
  langs:
  - csharp
  - vb
  name: Command(int)
  nameWithType: ReturnBook.Command.Command(int)
  fullName: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Command(int)
  type: Constructor
  source:
    remote:
      path: src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
      branch: master
      repo: https://github.com/ppucik/AdaSoftLibrary.git
    id: .ctor
    path: ../src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
    startLine: 16
  assemblies:
  - AdaSoftLibrary.Application
  namespace: AdaSoftLibrary.Application.Books.Commands
  syntax:
    content: public Command(int id)
    parameters:
    - id: id
      type: System.Int32
    content.vb: Public Sub New(id As Integer)
  overload: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor*
  nameWithType.vb: ReturnBook.Command.New(Integer)
  fullName.vb: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.New(Integer)
  name.vb: New(Integer)
- uid: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
  commentId: P:AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
  id: Id
  parent: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: ReturnBook.Command.Id
  fullName: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
  type: Property
  source:
    remote:
      path: src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
      branch: master
      repo: https://github.com/ppucik/AdaSoftLibrary.git
    id: Id
    path: ../src/AdaSoftLibrary.Application/Books/Commands/ReturnBook.cs
    startLine: 17
  assemblies:
  - AdaSoftLibrary.Application
  namespace: AdaSoftLibrary.Application.Books.Commands
  syntax:
    content: public int Id { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Id As Integer
  overload: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id*
references:
- uid: AdaSoftLibrary.Application.Books.Commands
  commentId: N:AdaSoftLibrary.Application.Books.Commands
  href: AdaSoftLibrary.html
  name: AdaSoftLibrary.Application.Books.Commands
  nameWithType: AdaSoftLibrary.Application.Books.Commands
  fullName: AdaSoftLibrary.Application.Books.Commands
  spec.csharp:
  - uid: AdaSoftLibrary
    name: AdaSoftLibrary
    href: AdaSoftLibrary.html
  - name: .
  - uid: AdaSoftLibrary.Application
    name: Application
    href: AdaSoftLibrary.Application.html
  - name: .
  - uid: AdaSoftLibrary.Application.Books
    name: Books
    href: AdaSoftLibrary.Application.Books.html
  - name: .
  - uid: AdaSoftLibrary.Application.Books.Commands
    name: Commands
    href: AdaSoftLibrary.Application.Books.Commands.html
  spec.vb:
  - uid: AdaSoftLibrary
    name: AdaSoftLibrary
    href: AdaSoftLibrary.html
  - name: .
  - uid: AdaSoftLibrary.Application
    name: Application
    href: AdaSoftLibrary.Application.html
  - name: .
  - uid: AdaSoftLibrary.Application.Books
    name: Books
    href: AdaSoftLibrary.Application.Books.html
  - name: .
  - uid: AdaSoftLibrary.Application.Books.Commands
    name: Commands
    href: AdaSoftLibrary.Application.Books.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{MediatR.Unit}
  commentId: T:MediatR.IRequest{MediatR.Unit}
  parent: MediatR
  definition: MediatR.IRequest`1
  name: IRequest<Unit>
  nameWithType: IRequest<Unit>
  fullName: MediatR.IRequest<MediatR.Unit>
  nameWithType.vb: IRequest(Of Unit)
  fullName.vb: MediatR.IRequest(Of MediatR.Unit)
  name.vb: IRequest(Of Unit)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: MediatR.Unit
    name: Unit
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: MediatR.Unit
    name: Unit
    isExternal: true
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor*
  commentId: Overload:AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.#ctor
  href: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.html#AdaSoftLibrary_Application_Books_Commands_ReturnBook_Command__ctor_System_Int32_
  name: Command
  nameWithType: ReturnBook.Command.Command
  fullName: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Command
  nameWithType.vb: ReturnBook.Command.New
  fullName.vb: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.New
  name.vb: New
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id*
  commentId: Overload:AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
  href: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.html#AdaSoftLibrary_Application_Books_Commands_ReturnBook_Command_Id
  name: Id
  nameWithType: ReturnBook.Command.Id
  fullName: AdaSoftLibrary.Application.Books.Commands.ReturnBook.Command.Id
